### PR TITLE
Android 3.0.8 version

### PR DESCRIPTION
**Pull request by Astrovic**
Android 3.0.8 version

### CODE REVIEW

**Comment by TinyGiantDigital** [comment]
Hi, does this version offload the Google Play Service to the new ti.playservices or is it just recompiled for SDK 7?

**Comment by Astrovic** [comment]
@TinyGiantDigital it's just recompiled for SDK 7

**Comment by jaceaser** [comment]
Is there a reason why untracked exceptions is not supported in the Android version?

**Comment by Astrovic** [comment]
Sorry, I don't know.. I've only recompiled the module

**Comment by Astrovic** [comment]
Thanks to @caffeinalab I create a new module version that uses ti.playservices: https://github.com/Astrovic/Ti.GA

**Comment by hansemannn** [comment]
Hey @Astrovic, we just received [this request](https://jira.appcelerator.org/browse/AC-5574) that sounds like something your module update fixes. Do you have an idea? Thanks :-)

**Comment by Astrovic** [comment]
Ti.GA 4.0.1 have not lib folder or jar files, it uses only ti.playservices
Maybe he aren't using the last module version.

**Comment by jsrsonu** [comment]
Hey @Astrovic .I downloaded from here https://github.com/Astrovic/Ti.GA/tree/master/Android/dist
Sharing screenshots in jar files are present.Could you please elaborate little bit how to use Ti.GA module and which is the latest one.Thanks @hansemannn for taking this forward.
screen shot 2018-02-07 at 9 57 50 am

**Comment by jsrsonu** [comment]
hey @Astrovic .Could you please explain it more ? How to use it and which is the latest version ?Thanks.

**Comment by Astrovic** [comment]
Hi @jsrsonu 
You're right, I removed the libraries later, because otherwise I could not build the module. But in fact without the libraries, the module does not work properly. Unfortunately I had not tested the changes well yet. So this version does not work as it should :(

**Comment by Astrovic** [comment]
@jsrsonu @hansemannn 
I sent a new PR that solve the issue: https://github.com/benbahrenburg/Ti.GA/pull/23/files
All you need is to edit Android Manifest: https://github.com/Astrovic/Ti.GA/blob/master/README.md#android-specifications

**Pull request merged**
