### PR TITLE
Update manifest

### PR DESCRIPTION
**Pull request by developer82**
Add arm64-v8a to architecture and fix minsdk to GA release. Without both settings module would compile but make app crash.

### CODE REVIEW

**Comment by timoa** [comment]
+1 👍

**Comment by jwogan5** [comment]
I see that you updated the manifest to add are64-v8a to allow it to build. Before adding that it would not build.  But once I did that locally it still failed because it needs 64 bit so files in those directories. Do you know if this module is going to be updated to support 64 bit android?   I was trying to run on a samsung galaxy s8 and if I created a new folder in libs labelled arm64-v8a and copied the .so file from the x86 folder it would stop throwing the error that it could not link the file but then it started throwing the error that the .so file was 32 bit and not 64 bit.

**Comment by m1ga** [comment]
@jwogan5 clean your build folder and create the `libs/arm64-v8a` if it is not created automatically. Then it should build fine.

**Comment by jwogan5** [comment]
@m1ga 

  Thanks for the quick response.  I have the folder created, build directory cleaned and the manifest file updated.  When I try to run on the samsung galaxy s8 the error below is what I get when the app tries to start and crashes. I created the arm64-v8a folder and coped the libti.ga.
so from one of the other folders into it.  If I do not copy the file I get an error that it cant find the libti.ga.so file.   If I do copy the file I get the following error as stated above.

[ERROR] TiApplication: (KrollRuntimeThread) [11,813] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.commercial.imt2-2/lib/arm64/libti.ga.
so" is 32-bit instead of 64-bit; Titanium 7.0.0,2017/12/05 13:30,undefined
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.commercial.imt2-2/lib/arm64/libti.ga.so" is 32-bit instead of 64-bit

[ERROR] TiApplication:  at java.lang.Runtime.loadLibrary0(Runtime.java:977)
[ERROR] TiApplication:  at java.lang.System.loadLibrary(System.java:1567)
[ERROR] TiApplication:  at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] TiApplication:  at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] TiApplication:  at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] TiApplication:  at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)

**Comment by developer82** [comment]
@jwogan5 You should completely delete the `libs` folder before compiling the module.

**Comment by jwogan5** [comment]
@developer82 

  Thanks for the hint.  I was trying to just use the module that was already built without the arm64.  So I cleaned everything out and removed the libs folder. I then ran appc run -p android --build-only and it gets to the ndk part and then throws the following error.  I appreciate all your assistance in getting the module built.  I am trying to release an update to an app today or tomorrow and need this or I have to go back to 6.3.0 SDK.

[INFO]  Producing [ModuleName]Bootstrap files using /Users/jason.wogan/work/buildtiga/build/generated/json/org/appcelerator/titanium/bindings/tiga.json
Generating BootstrapJS.cpp from bootstrap.js
[INFO]  Verifying build architectures
[INFO]  No native compiled libraries found, assume architectures are sane
[INFO]  Running the Android NDK ndk-build
[ERROR] Failed to run ndk-build
[ERROR]   
[ERROR] /Users/jason.wogan/work/buildtiga/build/generated/obj/local/arm64-v8a/objs/ti.ga/ti.ga.TigaModule.o: In function `titanium::TypeConverter::javaLongToJsNumber(v8::Isolate*, _JNIEnv*, long)':
[ERROR] /Users/jason.wogan/Library/Application Support/Titanium/mobilesdk/osx/7.0.0.GA/android/native/include/TypeConverter.h:54: undefined reference to `titanium::TypeConverter::javaLongToJsNumber(v8::Isolate*, long)'
[ERROR] clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] make: *** [/Users/jason.wogan/work/buildtiga/build/generated/obj/local/arm64-v8a/libti.ga.so] Error 1

**Comment by m1ga** [comment]
@jwogan5 do you just need the binary without changes?
http://migaweb.de/ti.ga-android-3.0.8.zip
I've added the missing  arm64-v8a architecture. It compilies (`appc ti build -p android -b`) without any further changes besides adding the arch and creating the libs/ arm64-v8a folder.

**Comment by jwogan5** [comment]
Thank you all soooo much. That file is all I needed and now ti.ga is running on SDK 7. I appreciate your quick responses and assistance.

**Comment by Nathanw** [comment]
Trying to get this to work in my app but after putting in the files provided by @m1ga I am getting the following error when building my app:
```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/CampaignTrackingReceiver;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/CampaignTrackingService;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/ExceptionParser;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/ExceptionReporter;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/GoogleAnalytics;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/HitBuilders;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/HitBuilders$AppViewBuilder;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/HitBuilders$EventBuilder;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/HitBuilders$ExceptionBuilder;
[ERROR]
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR]         at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR]         at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR]         at com.android.dx.command.Main.main(Main.java:94)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR]         ... 4 more
```

**Comment by m1ga** [comment]
@Nathanw that is because you are using another module that uses play-services. The module doesn't use `ti-playservice` yet so you need to strip the jars to make it work

**Comment by Nathanw** [comment]
@m1ga Thanks! There also seems to be an issue with the `addScreenView` method because the Android version expects 2 parameters but the iOS version seems to expect 1. I can't find this documented anywhere do you know if this is intended functionality?

**Comment by jwogan5** [comment]
@Nathanw 
  For the addScreenView just do the following to mimic the old way.

  Alloy.Globals.tracker.addScreenView('your_screen', {});

**Comment by slash-84** [comment]
@jwogan5 the error you provide in https://github.com/benbahrenburg/Ti.GA/pull/18#issuecomment-351445159 should be fixed with https://github.com/benbahrenburg/Ti.GA/pull/25

let me know if it helps :)

**Comment by kerberosargos** [comment]
Hello I am getting error as below on Android 9 (Pie) This issue is about Ti.GA?

```
02-12 12:54:37.901 13804 13804 E AndroidRuntime: FATAL EXCEPTION: main

02-12 12:54:37.901 13804 13804 E AndroidRuntime: Process: com.sizebiz.just.live.basketball, PID: 13804

02-12 12:54:37.901 13804 13804 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8titanium13TypeConverter18javaLongToJsNumberEPN2v87IsolateEx" referenced by "/data/app/com.sizebiz.just.live.basketball-RC7RJeH7thll-qM3q0WuKQ==/lib/arm64/libti.ga.so"...

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1669)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:139)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:113)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:207)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:113)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:135)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at com.sizebiz.just.live.basketball.JustLiveBasketballApplication.onCreate(JustLiveBasketballApplication.java:159)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.app.ActivityThread.access$1100(ActivityThread.java:200)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6692)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

02-12 12:54:37.901 13804 13804 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by AndreaVitale** [comment]
Same UnsatisfiedLinkError here on Android 8!!

**Comment by tomgiessel** [comment]
Same UnsatisfiedLinkError here on Android 9

**Comment by knemeth-vidatec** [comment]
Same UnsatisfiedLinkError here on Android 9

**Comment by m1ga** [comment]
@klaudia-dogfish if you are using the free version you need to upgrade to Firebase soon:
https://www.simoahava.com/analytics/google-analytics-for-mobile-sunset/
so it might be good to start soon.

I've recompiled the version with 8.0.2.GA and left the libraries in: http://migaweb.de/ti.ga-android-4.0.2_with_libs.zip
so it might conflict if you are using other ti.playservices modules.

There is also this PR: https://github.com/benbahrenburg/Ti.GA/pull/29
where I've set a fixed ti.playservice version in case you use other modules

**Pull request closed without merging**
