### PR TITLE
Fix compilation errore due to conflict of library google-play-service…

### PR DESCRIPTION
**Pull request by nonno**
I tried to use this module in a project where I used ti.map too and it never worked on Android, because including library google-play-services.jar I had errors of class already defined.
So I removed the jar replacing it with a "base" version (I got it from ti.admob module) and a "analytics" version I created using ProGuard.
Now it works, either alone and in conjunction with ti.map and ti.admob, and module is also 2MB smaller.

### CODE REVIEW

**Comment by m1ga** [comment]
:+1:

**Comment by nonno** [comment]
Error I obtained before the fix was this one:
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;

**Comment by williamrijksen** [comment]
@benbahrenburg Created 1.0.2 dist for Android.

**Comment by mlimb** [comment]
What version of play services is this using? I can't even find the integer play services version in the timodule.xml

**Comment by nonno** [comment]
@mlimb I have no idea, I simply got the one used by @benbahrenburg and I splitted it

**Comment by sharpred** [comment]
I had the same error when compiling with Ti.cloudPush 3.4.0, I fixed it in my fork by using google play services rev 27, I did not need to split to use .base, .analytics etc.

**Comment by benbahrenburg** [comment]
Thanks @nonno I've manually merged these changes in with others I have.

@mlimb I think your comment about version is going to be important. I've asked AppC to provide the full version of the Google Play jar they are using. This will make sure everything is running on the same version.

**Comment by nonno** [comment]
It's good that you haven't abandoned your project, but it would have been better to merge my commits and after to change eventual mistakes. It's not pleasant to work many hours for solving problems on disappeared people's projects and to see your contributions vanishing.

**Comment by benbahrenburg** [comment]
@nonno I appreciate your help in going through the updates. Just as you stated I wanted to avoid the hours it would take to go through the merge process and the associated errors. That is why I did the merge manually.  I'm happy to add you as contributor to the read me file.  No ill will was meant, just trying to save time.

**Comment by nonno** [comment]
@benbahrenburg I don't care to be in readme file, I only like to see something in "Repositories contributed to" section of my profile, because unluckily I don't have often opportunities for working on github's projects. By the way, happy to see that this project is not abandoned and thanks for your work.

**Pull request closed without merging**
